const Router = require("express").Router;
const authRouter = require("./auth-router.js")
const categoryRouter = require("./category-router.js")
// const subCategoryRouter = require("./subcategory-router.js")
const productRouter = require("./product-router.js")
const productPhotoRouter = require("./product-photo-router.js")
const sliderRouter = require("./slider-router.js")
const promoRouter = require("./promo-router.js")
const propertyTypeRouter = require("./property-value-router.js")
const productProperties = require("./product-property-router.js")
const propertyRouter = require("./property-router.js")
const developerRouter = require("./developer-router.js")
const categoryPropertyRouter = require("./category-property-router.js")
const shopRouter = require("./shop-router.js")
const shopProductRouter = require("./shop-product-router.js")
const fileRouter = require("./file-router.js")
const getMethodRouter = require("./get-method-router.js")
const paymentMethodRouter = require("./payment-method-router.js")
const orderRouter = require("./order-router.js")
const orderProductRouter = require("./order-product-router.js")
const reviewRouter = require("./review-router.js")

const router = Router()

router.use("/auth", authRouter)
router.use(categoryRouter)
router.use(categoryPropertyRouter)
router.use(productRouter)
router.use(shopRouter)
router.use(productProperties)
router.use(productPhotoRouter)
router.use(shopProductRouter)
router.use(sliderRouter)
router.use(developerRouter)
router.use(promoRouter)
router.use(propertyTypeRouter)
router.use(propertyRouter)
router.use(fileRouter)
router.use(getMethodRouter)
router.use(paymentMethodRouter)
router.use(orderRouter)
router.use(orderProductRouter)
router.use(reviewRouter)

module.exports = router